vsd_ip: 
api_url: 
lab_fqdn:
domainDNS:
infrVsc1Name = 'vsc1.sdn40r8.lab'
VSC1_IP = "root@core:2031"
infrVsc2Name = 'vsc2.sdn40r8.lab'
VSC2_IP = "root@core:2032"
infrVsc3Name = 'vsc3.sdn40r8.lab'
VSC3_IP = "root@core:2033"
infrVsc4Name = 'vsc4.sdn40r8.lab'
VSC4_IP = "root@core:2034"
