---
- name: "Waiting until 20min for server to come back"
  local_action: wait_for port=22 host="{{ ansible_host }}" search_regex=OpenSSH delay=30 timeout=1200
  remote_user: dev
  become: false

- include: 1_docker_install.yml

