---
- hosts: localhost
  gather_facts: no
  remote_user: root

  vars:
    packet_token: "{{ lookup('file', '/home/dev/.packet_token') }}"
    project_id: "{{ lookup('file', '/home/dev/.packet_project_id') }}"
    dns_domain: "{{ lab_domain }}"

  pre_tasks:

    - name: Read instances settings from file
      include_vars: cfg/{{ nuage_release }}/packet-bmetals.yml

  tasks:

    - name: Removing a ssh key nuage-vns-inabox in packet.net
      packet_sshkey:
        label: "sdnlab-{{ project_id | regex_replace('^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-([0-9a-f]*)$', '\\1') }}"
        key: "{{ lookup('file', '/home/dev/.ssh/id_rsa.pub') }}"
        state: absent
        auth_token: "{{ packet_token }}"

    - name: Removing a Bare Metal server
      packet_device:
        project_id: "{{ project_id }}"
        hostnames: "{{ item.device_name }}"
        plan: "{{ item.bmetal_plan }}"
        facility: "{{ item.facility }}"
        operating_system: "{{ item.osystem }}"
        state: absent
        auth_token: "{{ packet_token }}"
      with_items: "{{ bmetals }}"


- hosts: localhost
  gather_facts: no

  tasks:

    - name: Are you sure?
      pause: prompt='This operation will overwrite build.yml and destroy host_vars! Press return to continue. Press Ctrl+c and then "a" to abort'

    - name: Destroy the host_vars directory and its contents
      file: path={{ playbook_dir }}/host_vars/ state=absent

    - name: Destroy the group_vars directory and its contents
      file: path={{ playbook_dir }}/group_vars/ state=absent

    - name: Destroy hosts file in the playbook directory
      file: path={{ playbook_dir }}/hosts state=absent

    - name: Destroy extras in the playbook directory
      file: path={{ playbook_dir }}/extras state=absent

    - name: Destroy yml files in the playbook directory
      file: path={{ playbook_dir }}/{{ item }} state=absent
      with_items:
        - nuage-install.yml
        - vsd-deploy.yml
        - vsd-postinstall.yml
        - vsc-profiles.yml
        - stat-predeploy.yml
        - stat-deploy.yml
        - nserver-deploy.yml
        - util-predeploy.yml
        - util-deploy.yml
        - reset-all-domains.yml
        - pk-create.yml
        - pk-create.sh
        - pk-reset.yml
        - pk-reset.sh
        - ovs-deploy.yml
        - nuage.sh
        - license.yml
        - health.yml
        - deploy-all.yml
        - webvirtmgr-deploy.yml
        - docker-deploy.yml
