---
# build.yml: Create your host and group var files from this
- hosts: localhost
  gather_facts: no
  roles:
    - build
  vars:
    ntp_server_list:
      - 192.168.0.12
    dns_server_list:
      - 192.168.0.12
    dns_domain: sdn40r8.lab
    public_if: bond0
    packet_token: "{{ lookup('file', '/home/dev/.packet_token') }}"
    project_id: "{{ lookup('file', '/home/dev/.packet_project_id') }}"
    nuage_license_key: "{{ lookup('file', '/home/dev/.nuage_license_key') }}"
    summary_file: "/home/dev/pk-sdnlab-stdalone/.summary"
    ssh_key:
    - "{{ lookup('file', '/home/dev/.ssh/id_rsa.pub') }}"
    servers: 
      - { hostname: ns1.sdn40r8.lab,
          description: "name, ntp and dhcp server" ,
          inventory: nserver ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          disk_GB: 20 ,
          image_qcow2: /home/dev/images/centos7.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/centos7.qcow2" ,
          hypervisor: core,
          ansible_host: 'centos@core:2012' ,
          gateway: 192.168.0.1,
          ntpservers: local , 
          nameservers: [ 8.8.8.8 , 4.4.4.4 ] ,
          interfaces: [
            { name: eth0 , bridge: external, ip: 192.168.0.12 , netmask: 255.255.255.0 },
            { name: eth1 , bridge: wan, ip: 10.250.250.2 , netmask: 255.255.255.0 },
            { name: eth2 , bridge: external, ip: 80.80.80.2 , netmask: 255.255.255.0 }
          ] ,
          pat_rules: [
            { protocol: tcp , interface: bond0 , port: 53 , dest_port: 53 },
            { protocol: udp , interface: bond0 , port: 53 , dest_port: 53 },
            { protocol: udp , interface: bond0 , port: 123 , dest_port: 123 }
          ]
         }
      - { hostname: vsd1.sdn40r8.lab,
          description: "Nuage Stand-Alone VSD, management plane" ,
          inventory: vsd ,
          Is_NM_enabled: true ,
          memory: 16777216 ,
          vcpu_num: 8 ,
          image_qcow2: /home/dev/images/vsd40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/vsd40r8.qcow2" ,
          hypervisor: core,
          ansible_host: 'root@core:2020' ,
          gateway: 192.168.0.1,
          interfaces: [
          { name: eth0 ,
            bridge: core,
            ip: 192.168.0.20 ,
            netmask: 255.255.255.0 }
          ], 
          pat_rules: [
            { protocol: tcp , interface: bond0 , port: 8443 , dest_port: 8443 },
            { protocol: tcp , interface: bond0 , port: 5222 , dest_port: 5222 },
            { protocol: tcp , interface: bond0 , port: 61613 , dest_port: 61613 },
            { protocol: tcp , interface: bond0 , port: 61614 , dest_port: 61614 },
            { protocol: tcp , interface: bond0 , port: 7443 , dest_port: 7443 },
            { protocol: tcp , interface: bond0 , port: 39090, dest_port: 39090  }
          ]      
         }
      - { hostname: util.sdn40r8.lab,
          description: "Util server for Nuage VNS" ,
          inventory: util ,
          Is_NM_enabled: true ,
          No_cloud_init: true ,
          Guestfish: true ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          image_qcow2: /home/dev/images/util40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/util40r8.qcow2" ,
          hypervisor: core,
          ansible_host: 'root@core:2027' ,
          gateway: 192.168.0.1,
          interfaces: [
          { name: eth0 ,
            bridge: core,
            ip: 192.168.0.27 ,
            netmask: 255.255.255.0 }
          ],      
          pat_rules: [
            { protocol: tcp , interface: bond0 , port: 11443 , dest_port: 11443 },
            { protocol: tcp , interface: bond0 , port: 12443 , dest_port: 12443 },
            { protocol: tcp , interface: bond0 , port: 514 , dest_port: 514 },
            { protocol: tcp , interface: bond0 , port: 443 , dest_port: 443 },
            { protocol: tcp , interface: bond0 , port: 29090, dest_port: 29090  }
          ]      
         }
      - { hostname: stat.sdn40r8.lab,
          description: "Stat server based on ElasticSearch" ,
          inventory: stat ,
          Is_NM_enabled: true ,
          No_cloud_init: true ,
          Guestfish: true ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          image_qcow2: /home/dev/images/stat40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/stat40r8.qcow2" ,
          hypervisor: core ,
          ansible_host: 'root@core:2028' ,
          gateway: 192.168.0.1,
          interfaces: [
          { name: eth0 ,
            bridge: core,
            ip: 192.168.0.28 ,
            netmask: 255.255.255.0 }
          ],
          pat_rules: [
            { protocol: tcp , interface: bond0 , port: 6200 , dest_port: 6200 },
            { protocol: tcp , interface: bond0 , port: 5601 , dest_port: 5601 },
          ]      
         }
      - { hostname: head1.sdn40r8.lab,
          description: "NSG-v Head End at Datacenter" ,
          inventory: nsg ,
          No_cloud_init: true ,
          rtl8139: true ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          image_qcow2: /home/dev/images/nsg40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/nsg40r8.qcow2" ,
          hypervisor: core ,
          interfaces: [
          { name: port1 ,
            bridge: wan },
          { name: port2 ,
            bridge: inet },
          { name: port3 ,
            bridge: core }
#          ],      
#          pat_rules: [
#            { protocol: udp , interface: bond0 , port: 4789 , dest_port: 4789 },
#            { protocol: udp , interface: bond0 , port: 4500 , dest_port: 4500 },
#            { protocol: udp , interface: bond0 , port: 500 , dest_port: 500 },
#            { protocol: tcp , interface: bond0 , port: 179 , dest_port: 179 },
          ]      
         }
      - { hostname: head2.sdn40r8.lab,
          description: "NSG-v Head End at Datacenter" ,
          inventory: nsg ,
          No_cloud_init: true ,
          rtl8139: true ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          image_qcow2: /home/dev/images/nsg40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/nsg40r8.qcow2" ,
          hypervisor: core ,
          interfaces: [
          { name: port1 ,
            bridge: wan },
          { name: port2 ,
            bridge: inet },
          { name: port3 ,
            bridge: core }
#          ],      
#          pat_rules: [
#            { protocol: udp , interface: bond0 , port: 4789 , dest_port: 4789 },
#            { protocol: udp , interface: bond0 , port: 4500 , dest_port: 4500 },
#            { protocol: udp , interface: bond0 , port: 500 , dest_port: 500 },
#            { protocol: tcp , interface: bond0 , port: 179 , dest_port: 179 },
          ]      
         }
      - { hostname: nsg-br.sdn40r8.lab,
          description: "NSG-v Head End at Datacenter" ,
          inventory: nsg ,
          No_cloud_init: true ,
          rtl8139: true ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          image_qcow2: /home/dev/images/nsg40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/nsg40r8.qcow2" ,
          hypervisor: core ,
          interfaces: [
          { name: port1 ,
            bridge: wan },
          { name: port2 ,
            bridge: inet },
          { name: port3 ,
            bridge: core }
#          ],      
#          pat_rules: [
#            { protocol: udp , interface: bond0 , port: 4789 , dest_port: 4789 },
#            { protocol: udp , interface: bond0 , port: 4500 , dest_port: 4500 },
#            { protocol: udp , interface: bond0 , port: 500 , dest_port: 500 },
#            { protocol: tcp , interface: bond0 , port: 179 , dest_port: 179 },
          ]      
         }
      - { hostname: nsg1.sdn40r8.lab,
      - { hostname: nsg1.sdn40r8.lab,
          description: "NSG-v at Branch 1" ,
          inventory: nsg ,
          No_cloud_init: true ,
          rtl8139: true ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          image_qcow2: /home/dev/images/nsg40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/nsg40r8.qcow2" ,
          hypervisor: sdwan1 ,
          interfaces: [
          { name: port1 ,
            bridge: wan },
          { name: port2 ,
            bridge: inet },
          { name: port3 ,
            bridge: branch1}
#          ],      
#          pat_rules: [
#            { protocol: udp , interface: bond0 , port: 4789 , dest_port: 4789 },
#            { protocol: udp , interface: bond0 , port: 4500 , dest_port: 4500 },
#            { protocol: udp , interface: bond0 , port: 500 , dest_port: 500 },
#            { protocol: tcp , interface: bond0 , port: 179 , dest_port: 179 },
          ]      
         }
      - { hostname: nsg2.sdn40r8.lab,
          description: "NSG-v at Branch 2" ,
          inventory: nsg ,
          No_cloud_init: true ,
          rtl8139: true ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          image_qcow2: /home/dev/images/nsg40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/nsg40r8.qcow2" ,
          hypervisor: sdwan2 ,
          interfaces: [
          { name: port1 ,
            bridge: wan },
          { name: port2 ,
            bridge: inet },
          { name: port3 ,
            bridge: branch2}
#          ],      
#          pat_rules: [
#            { protocol: udp , interface: bond0 , port: 4789 , dest_port: 4789 },
#            { protocol: udp , interface: bond0 , port: 4500 , dest_port: 4500 },
#            { protocol: udp , interface: bond0 , port: 500 , dest_port: 500 },
#            { protocol: tcp , interface: bond0 , port: 179 , dest_port: 179 },
          ]      
         }
      - { hostname: cli1.sdn40r8.lab,
          description: "client at branch1" ,
          inventory: client ,
          No_cloud_init: true ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          image_qcow2: /home/dev/images/centos7-reverse.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/ubuntu.qcow2" ,
          hypervisor: sdwan1 ,
          interfaces: [
          { name: eth0 ,
            bridge: branch1 }
          ]
         }
      - { hostname: cli2.sdn40r8.lab,
          description: "client at branch2" ,
          inventory: client ,
          No_cloud_init: true ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          image_qcow2: /home/dev/images/centos7-reverse.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/ubuntu.qcow2" ,
          hypervisor: sdwan2 ,
          interfaces: [
          { name: eth0 ,
            bridge: branch2 }
          ]
         }
      - { hostname: virt.sdn40r8.lab,
          description: "webvirtmgr service" ,
          inventory: webvirtmgr ,
          memory: 4194304 ,
          vcpu_num: 2 ,
          disk_GB: 20 ,
          image_qcow2: /home/dev/images/centos7.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/centos7-reverse.qcow2" ,
          hypervisor: dc1 ,
          ansible_host: 'centos@dc1:2022' ,
          gateway: 192.168.0.4,
          interfaces: [
          { name: eth0 ,
            bridge: core,
            ip: 192.168.0.30 ,
            netmask: 255.255.255.0 }
          ],
          pat_rules: [
            { protocol: tcp , interface: bond0 , port: 8090 , dest_port: 8090 },
            { protocol: tcp , interface: bond0 , port: 6080 , dest_port: 6080 }
          ]
         }
    vsc_controllers:
      - { hostname: vsc1.sdn40r8.lab,
          description: "Nuage VSC - SDN controller" ,
          inventory: vsc ,
          image_qcow2: /home/dev/images/vsc40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/vsc40r8.qcow2" ,
          hypervisor: core ,
          vsc_cert_name: vsc1nsg , #tls profile
          vsc_passwd: admin ,
          ansible_host: 'root@core:2021' ,
          vsd_fqdn: vsd1.sdn40r8.lab,
          system_ip: 1.1.1.1,
          xmpp_username: vsc01,
          gateway: 192.168.0.1,
          interfaces: [
          { name: bof ,
            bridge: core },
          { name: control ,
            bridge: core,
            ip: 192.168.0.21 ,
            prefix: 24 }
          ],
          static_routes: [
            "0.0.0.0/0 next-hop 192.168.0.1" 
#          ],
#          pat_rules: [
#            { protocol: tcp , interface: bond0 , port: 56213 , dest_port: 56213 },
#            { protocol: tcp , interface: bond0 , port: 6633 , dest_port: 6633 },
#            { protocol: udp , interface: bond0 , port: 123 , dest_port: 123 },
#            { protocol: tcp , interface: bond0 , port: 7407 , dest_port: 7407 },
          ]      
        }      
      - { hostname: vsc2.sdn40r8.lab,
          description: "Nuage VSC - SDN controller" ,
          inventory: vsc ,
          image_qcow2: /home/dev/images/vsc40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/vsc40r8.qcow2" ,
          hypervisor: core ,
          vsc_cert_name: vsc2nsg ,  #tls profile
          vsc_passwd: admin ,
          ansible_host: 'root@core:2022' ,
          vsd_fqdn: vsd1.sdn40r8.lab,
          system_ip: 1.1.1.2 ,
          xmpp_username: vsc02,
          gateway: 192.168.0.1,
          interfaces: [
          { name: bof ,
            bridge: core },
          { name: control ,
            bridge: core,
            ip: 192.168.0.22 ,
            prefix: 24 }
          ] ,      
          pat_rules: [
            { protocol: tcp , interface: bond0 , port: 56213 , dest_port: 56213 },
            { protocol: tcp , interface: bond0 , port: 6633 , dest_port: 6633 },
            { protocol: udp , interface: bond0 , port: 123 , dest_port: 123 },
            { protocol: tcp , interface: bond0 , port: 7407 , dest_port: 7407 },
          ],      
          static_routes: [
            "0.0.0.0/0 next-hop 192.168.0.1" 
          ]
         }
      - { hostname: vsc3.sdn40r8.lab,
          description: "Nuage VSC - SDN controller" ,
          inventory: vsc ,
          image_qcow2: /home/dev/images/vsc40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/vsc40r8.qcow2" ,
          hypervisor: core ,
# tls profile not required:          vsc_cert_name: vsc3nsg ,
          vsc_passwd: admin ,
          ansible_host: 'root@core:2023' ,
          vsd_fqdn: vsd1.sdn40r8.lab,
          system_ip: 1.1.1.3 ,
          xmpp_username: vsc03,
          gateway: 192.168.0.1,
          interfaces: [
          { name: bof ,
            bridge: core },
          { name: control ,
            bridge: core,
            ip: 192.168.0.23 ,
            prefix: 24 }
          ] ,      
          static_routes: [
            "0.0.0.0/0 next-hop 192.168.0.1" 
          ]
         }
      - { hostname: vsc4.sdn40r8.lab,
          description: "Nuage VSC - SDN controller" ,
          inventory: vsc ,
          image_qcow2: /home/dev/images/vsc40r8.qcow2 ,
          image_url: "https://s3-us-west-2.amazonaws.com/nuage-demo-cala/40r8+files/vsc40r8.qcow2" ,
          hypervisor: core ,
# tls profile not required:          vsc_cert_name: vsc2nsg ,
          vsc_passwd: admin ,
          ansible_host: 'root@core:2024' ,
          vsd_fqdn: vsd1.sdn40r8.lab,
          system_ip: 1.1.1.4 ,
          xmpp_username: vsc04,
          gateway: 192.168.0.1,
          interfaces: [
          { name: bof ,
            bridge: core },
          { name: control ,
            bridge: core,
            ip: 192.168.0.24 ,
            prefix: 24 }
          ] ,      
          static_routes: [
            "0.0.0.0/0 next-hop 192.168.0.1" 
          ]
         }
