---
- name: Creating a ssh key nuage-vns-inabox in packet.net
  packet_sshkey:
    label: "sdnlab-{{ project_id | regex_replace('^[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-[0-9a-f]*-([0-9a-f]*)$', '\\1') }}"
    key: "{{ lookup('file', '/home/dev/.ssh/id_rsa.pub') }}"
    state: present
    auth_token: "{{ packet_token }}"

- name: Creating a Bare Metal server
  packet_device:
    project_id: "{{ project_id }}"
    hostnames: "{{ item.device_name }}"
    plan: "{{ item.bmetal_plan }}"
    facility: "{{ item.facility }}"
    operating_system: "{{ item.osystem }}"
    state: present
    auth_token: "{{ packet_token }}"
  with_items: "{{ bmetals }}"

- name: "Waiting up to 10min for server"
  pause:
    minutes: 10
