---

- name: "Getting the IP address from Packet server"
  local_action: command python {{playbook_dir}}/roles/pk-create/files/packet_get_ipaddr.py {{ project_id }} {{ packet_token }} {{ item.device_name }}
  register: pk_private_ip
  with_items: "{{ bmetals }}"

- name: "Getting the Public IP address from Packet server"
  local_action: command python {{playbook_dir}}/roles/pk-create/files/packet_get_ipaddr_pub.py {{ project_id }} {{ packet_token }} {{ item.device_name }}
  register: pk_public_ip
  with_items: "{{ bmetals }}"

- name: Create var
  set_fact: 
    ip_item: "{{ ip_item|default({}) | combine( { 'device_name': item.1.device_name , 'private_ip' : pk_private_ip.results[item.0].stdout } ) }}"
#  set_fact: ip_item="{ device_name: '{{ item.1.device_name }}' , private_ip: '{{ pk_private_ip.results[item.0].stdout }}'}"
  with_indexed_items: "{{ bmetals }}"
  register: ip_item_results

- name: debug
  debug: var=ip_item_results

- name: make a list
  set_fact: iphost_list='{{ ip_item_results.results | map(attribute='ansible_facts.ip_item') | list }}'

- name: debug
  debug: var=iphost_list

- name: Creating host_vars files of servers
  template: src=servers.j2 dest="{{ playbook_dir }}/host_vars/{{ item.1.device_name }}" backup=no
  with_indexed_items: "{{ bmetals }}"  

- name: "Adding records to inventory file under [bmetal]"
  lineinfile:
    dest: "{{playbook_dir}}/hosts"
    regexp: "^{{ item.1.device_name }} "
    insertafter: '^\[bmetal\]$'
    line: "{{ item.1.device_name }} ansible_host={{ pk_public_ip.results[item.0].stdout }} ansible_user=root"
  with_indexed_items: "{{ bmetals }}"

- name: "Adding IPs to host_vars files for vxlans"
  lineinfile:
    dest: "{{ playbook_dir }}/host_vars/{{ item[0].device_name }}"
    regexp: "^       vxlan_dest : {{ item[1].device_name }} ,$"
    line: '       vxlan_dest : {{ item[1].private_ip }} ,'
    backrefs: yes
  with_nested: 
    - "{{ bmetals }}"
    - "{{ iphost_list }}"

- name: "Adding IPs to inventory file under [bmetal]"
  replace:
    dest: "{{playbook_dir}}/hosts"
    regexp: "^(.*)ansible_host={{ item.1.device_name }}(.*)$"
    replace: '\1ansible_host={{ pk_public_ip.results[item.0].stdout }}\2'
  with_indexed_items: "{{ bmetals }}"

- name: "Create bmetal groupvar file"
  template: src=bmetal.j2 dest="{{ playbook_dir }}/group_vars/bmetal" backup=no

- name: list of host files and store it in register
  raw: find {{ playbook_dir }}/host_vars -type f -name "*{{ domain }}"
  register: host_files

#- debug:
#    msg: "{{ host_files.stdout_lines }}"  

- name: create array of public_ips and hosts
  raw: grep 147 hosts | sed -e 's/^\(.*\) .*=\(.*\) .*$/\1 \2/' | grep -v {{ dns_domain }}
  register: bmetal_array

#- debug:
#    msg: "{{ bmetal_array.stdout_lines }}"  

- name: "Adding records to hostvars  under [bmetal]"
  lineinfile:
    dest: "{{ item[1] }}"
    regexp: "^hypervisor: {{ item[0] | regex_replace('^(.*) .*$','\\1') }}$"
    line: "hypervisor: {{ item[0] | regex_replace('^.* (.*)$','\\1') }}"
    backrefs: yes
  with_nested: 
     - "{{ bmetal_array.stdout_lines }}"
     - "{{ host_files.stdout_lines }}"
